let topics = [
  "Introducing Yourself",
  "Asking About Someone's Day",
  "Discussing Hobbies and Interests",
  "Travel Experiences",
  "Food and Cooking",
  "Health and Fitness",
  "Fashion and Clothing",
  "Movies and Television",
  "Music and Concerts",
  "Art and Culture",
  "Books and Literature",
  "Sports and Activities",
  "Technology and Gadgets",
  "Social Media",
  "Current Events",
  "Family and Relationships",
  "Pets and Animals",
  "Weather and Seasons",
  "Childhood Memories",
  "Future Plans and Goals",
  "Education and School",
  "Work and Careers",
  "Business and Entrepreneurship",
  "Real Estate and Housing",
  "Personal Finance",
  "Politics and Government",
  "Environmental Issues",
  "Science and Innovation",
  "History and Historical Events",
  "Cars and Transportation",
  "Home Decor",
  "Gardening and Landscaping",
  "Celebrations and Holidays",
  "Public Speaking",
  "Personal Development",
  "Religion and Spirituality",
  "Charity and Volunteering",
  "Immigration and Cultures",
  "Language Learning",
  "Jokes and Humor",
  "Shopping and Sales",
  "Video Games",
  "DIY Projects",
  "Hiking and Outdoor Activities",
  "Photography",
  "Crime and Justice",
  "Celebrity Gossip",
  "Astrology and Horoscopes",
  "Recycling and Sustainability",
  "Beach Vacations",
  "Wine Tasting",
  "Coffee Culture",
  "Online Learning",
  "Parenting and Childcare",
  "Retirement Planning",
  "Yoga and Meditation",
  "Wildlife Conservation",
  "Podcasts",
  "Space Exploration",
  "Nutrition and Dieting",
  "Digital Privacy",
  "Cosmetics and Beauty",
  "Camping and Adventure Travel",
  "Public Transport",
  "Extreme Sports",
  "Mental Health",
  "Tattoos and Body Art",
  "Architecture and Design",
  "Magic and Illusions",
  "Virtual Reality",
  "Online Dating",
  "Thrift Shopping",
  "Classic Cars",
  "Learning a Musical Instrument",
  "Stand-up Comedy",
  "Science Fiction and Fantasy",
  "Time Management",
  "Conspiracy Theories",
  "Cryptocurrency",
  "Sustainable Living",
  "Freelancing and Gig Economy",
  "Marathon Running",
  "Robotics and AI",
  "Organic Food and Farming",
  "Craft Beer Brewing",
  "Personal Branding",
  "Conflict Resolution",
  "Ethical Fashion",
  "Street Art",
  "Antique Collecting",
  "Procrastination and Productivity",
  "Minimalist Living",
  "Coding and Programming",
  "3D Printing",
  "Microbreweries and Distilleries",
  "Renewable Energy",
  "Dreams and Their Meanings",
  "Unusual Hobbies",
  "Adventure Sports",
  "UFOs and Aliens",
];

// 创建一个备份的话题列表
let backupTopics = [...topics];

export function pickRandomTopics(n: number): string[] {
  let randomTopics = [];
  for (let i = 0; i < n; i++) {
    if (topics.length === 0) {
      topics = [...backupTopics]; // 从备份列表中重新填充话题列表
    }
    let randomIndex = Math.floor(Math.random() * topics.length);
    randomTopics.push(topics[randomIndex]);
    topics.splice(randomIndex, 1);
  }
  return randomTopics;
}
